### ISSUE TITLE
Background animation problem

### ISSUE THREAD

**Issue by MadPeachTM** [voidcosmos/voidcosmos.github.io#1]
If you open voidcosmos.github.io and then go to another tab for a long time (and also change width of browser), then after coming back you get several lines of stars like on screenshot:
![stars](https://user-images.githubusercontent.com/11052469/66701378-6e700d00-ed04-11e9-8133-171df9a4c55a.PNG)
.
nice post btw https://dev.to/nyagarcia/the-art-of-refactoring-5-tips-to-write-better-code-12if

**Comment by zaldih** [comment]
Thanks for open the issue, mate!
I am not surprised that it has such failures. We develop the web in a short time without paying too much attention. I will see how it could be fixed :) .

Regarding the post... @NyaGarcia ,  **we invoke you!**

**Comment by NyaGarcia** [comment]
Aw thanks @FanatiG! I definitely wasn't expecting such a nice comment in an issue ❤️
Regarding the issue, will fix it as soon as possible, thanks for letting us know :)
